################################################################################
# Set the global variables
default_env: production              # defines the environment

################################################################################
# List of error strings. Step will fail if one of these strings is detected.
error_strings:
  [
    "Server Error",
    "Error: Page Not Found"
  ]

################################################################################
# Environment specific variables

production:
  home: http://shoestore-manheim.rhcloud.com/

test:
  